[pytest]
# Automatically look for tests inside the src directory
pythonpath = . src

# Default flags so you don't have to type them every time in the terminal
# -v: Verbose output
# -ra: Show extra test summary info for all except passed tests
# --strict-markers: Treat unregistered custom markers as errors
addopts = -v -ra --strict-markers

# Tell pytest where to look for test files
testpaths = tests

# Explicitly ignore tracking warnings from third-party libraries (Snowflake, Langchain etc.)
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning