-- Snowflake Infrastructure Setup Script (Hybrid Approach)
-- Run this as ACCOUNTADMIN in a Snowflake Worksheet

-- 1. Create Warehouse
CREATE OR REPLACE WAREHOUSE ECOMMERCE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE
  COMMENT = 'Main warehouse for Ecommerce Analytics platform';

-- 2. Create Database
CREATE OR REPLACE DATABASE ECOMMERCE_ANALYTICS;

-- 3. Create Schemas
USE DATABASE ECOMMERCE_ANALYTICS;
CREATE OR REPLACE SCHEMA RAW_DATA;          -- Raw data landing
CREATE OR REPLACE SCHEMA OLIST;             -- dbt seeds / default
CREATE OR REPLACE SCHEMA OLIST_STAGING;      -- dbt staging layer
CREATE OR REPLACE SCHEMA OLIST_INTERMEDIATE; -- dbt intermediate layer
CREATE OR REPLACE SCHEMA OLIST_MART;         -- Final analytics models

-- 4. Create Roles
CREATE OR REPLACE ROLE ECOMMERCE_TRANSFORMER;
CREATE OR REPLACE ROLE ECOMMERCE_AGENT;

-- 5. Create Users
CREATE OR REPLACE USER ECOMMERCE_DBT_USER 
  PASSWORD = 'ExamplePassword!2025' 
  DEFAULT_ROLE = ECOMMERCE_TRANSFORMER 
  DEFAULT_WAREHOUSE = ECOMMERCE_WH;

CREATE OR REPLACE USER ECOMMERCE_AI_USER 
  PASSWORD = 'ExamplePassword!2026' 
  DEFAULT_ROLE = ECOMMERCE_AGENT 
  DEFAULT_WAREHOUSE = ECOMMERCE_WH;

-- 6. Grant Warehouse Usage
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ECOMMERCE_TRANSFORMER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ECOMMERCE_AGENT;

-- 7. Grant Database/Schema Permissions to ECOMMERCE_TRANSFORMER
GRANT ALL PRIVILEGES ON DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_ANALYTICS.RAW_DATA TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_ANALYTICS.OLIST TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_ANALYTICS.OLIST_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_ANALYTICS.OLIST_INTERMEDIATE TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_ANALYTICS.OLIST_MART TO ROLE ECOMMERCE_TRANSFORMER;

-- 8. Grant Restricted Permissions to ECOMMERCE_AGENT (The TTS Agent)
GRANT USAGE ON DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_AGENT;
GRANT USAGE ON SCHEMA ECOMMERCE_ANALYTICS.OLIST_MART TO ROLE ECOMMERCE_AGENT;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_ANALYTICS.OLIST_MART TO ROLE ECOMMERCE_AGENT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_ANALYTICS.OLIST_MART TO ROLE ECOMMERCE_AGENT;

-- 9. Grant Role to Users
GRANT ROLE ECOMMERCE_TRANSFORMER TO USER ECOMMERCE_DBT_USER;
GRANT ROLE ECOMMERCE_AGENT TO USER ECOMMERCE_AI_USER;

-- 11. Grant Cortex AI Permissions (for Embeddings and Semantic Search)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ECOMMERCE_TRANSFORMER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ECOMMERCE_AGENT;

SELECT 'Snowflake environment setup complete!' AS result;
